version: '3.8'

services:      
  db:
    container_name: mssql_admin
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "localPassword1"
    volumes:
      - ./DBSeed:/home/dbseed/:cached
      - db:/var/opt/mssql/data
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_URLS: http://+:5000
    depends_on:
      - db
      
volumes:
 db:
   driver: local